
const wordsInfo = {
    "RINOCERONTE": "El rinoceronte blanco del norte: Los dos últimos rinocerontes blancos del norte que existen resultan ser hembras, ya que el último macho murió en marzo de 2018. Sudán, el macho de 45 años estaba bajo guardia armada en el Ol Pejeta Conservancy de Kenia cuando falleció a causa de la vejez y de una infección. Las dos hembras tampoco pueden dar a luz, lo que hace muy improbable la introducción de una nueva generación de la especie. Los científicos están trabajando en el uso de células sexuales extraídas y en la FIV para dar a luz a un rinoceronte blanco del norte creado en laboratorio. Causa de la extinción: la caza furtiva ha diezmado esta población y la pérdida de hábitat también ha contribuido a llevar al rinoceronte al borde de la extinción.",
    "GUACAMAYO": "El guacamayo de Spix: Se creía extinguido en su hábitat natural, existe actualmente en cautividad y su número se sitúa entre 60 y 80 ejemplares. También se le conoce como guacamayo azul porque es conocido por sus plumas de color azul intenso. Causa de la extinción: el guacamayo de Spix se extinguió en la naturaleza debido a la destrucción del hábitat, la captura ilegal y el comercio.",
    "LOBO": "El lobo de Tasmania: El tilacino, un carnívoro también conocido como tigre de Tasmania y lobo de Tasmania, era un marsupial (principalmente) nocturno que se alimentaba de roedores y canguros. Aunque los tilacinos parecían feroces, en realidad eran bastante tímidos y, según Live Science, podían ser capturados sin luchar. Los informes sobre avistamientos de tilacinos han sido tan frecuentes en el último siglo que han provocado una investigación sobre su existencia. Causa de la extinción: se cree que las poblaciones de dingos amenazaron al Thylacine hasta su extinción, además de la caza excesiva por parte de los humanos.",
    "PALOMA": "La paloma pasajera: Se calcula que la población de palomas pasajeras se contaba por millones -y posiblemente miles de millones- cuando los primeros europeos empezaron a asentarse en América. MentalFloss informa de que Wisconsin albergaba el mayor lugar de anidación conocido a finales del siglo XIX. Causa de la extinción: los seres humanos cazaron la paloma y la consumieron hasta el punto de extinguirla. El último pájaro conocido murió en cautividad en el zoológico de Cincinnati en 1914.",
    "SAPO": "El sapo dorado: Esta no es la única especie que ha desaparecido en los últimos 40 años, pero podría ser la más brillante. Este pequeño sapo fue visto por última vez en 1989 en un bosque tropical de Costa Rica antes de ser declarado extinto en 1994. Se cree que la quitridiomicosis, una enfermedad cutánea mortal, diezmó esta población de sapos que ya era vulnerable gracias a lo que Science denomina hábitat limitado y población reducida. Causa de la extinción: la contaminación, el calentamiento global y las infecciones cutáneas por quitridio provocaron la extinción de esta especie.",
    "LEOPARDO": "El leopardo de Zanzíbar: Es una de las varias subespecies de leopardo, tuvo su hogar en el archipiélago de Zanzíbar, en Tanzania. Todavía no está claro si este gran felino está técnicamente extinguido: hay avistamientos ocasionales no confirmados. Causa de la extinción: el leopardo se extinguió gracias a la creencia de que estos animales eran mantenidos por brujas; por esta razón, los lugareños los cazaron agresivamente. No ayudó que el gobierno estuviera en la campaña de exterminio de las criaturas. A mediados de los 90 hubo un efímero esfuerzo de conservación, pero se consideró que era demasiado poco y demasiado tarde.",
    "TIGRE": "El tigre de Java: Era originario de la isla indonesia de Java. En el siglo XIX eran tan comunes que los nativos de la isla los consideraban plagas, pero a medida que la isla se desarrollaba su población disminuyó. En la década de 1950, sólo quedaban 20 tigres. Causa de la extinción: la pérdida de hábitat y el desarrollo agrícola provocaron un grave descenso de la población. Los esfuerzos de conservación en los años 40 y 50 fueron infructuosos debido a la falta de terreno y planificación adecuados.",
    "BOA": "Boa excavadora de la Isla Redonda: Originaria de Isla Redonda, una pequeña isla frente a la costa de Mauricio, la boa excavadora de Isla Redonda prefería vivir en las capas superiores del suelo de las laderas volcánicas. Antes se encontraba en otras islas de Mauricio, pero su población había disminuido en la década de 1940, y sólo se pudo encontrar en Isla Redonda después de 1949. Se vio por última vez en 1975. Causa de la extinción: la introducción de especies no autóctonas de conejos y cabras en la isla destruyó la vegetación y alteró el hábitat de la boa, lo que provocó su eventual extinción.",
    "MARIPOSA": "La mariposa blanca de Madeira: Fue encontrada en los valles de los bosques de Laurisilva, en las Islas Madeira de Portugal. El pariente más cercano de esta mariposa, la Gran Blanca, es común en toda Europa, África y Asia. Causa de la extinción: la pérdida de hábitat debido a la construcción, así como la contaminación por fertilizantes agrícolas, son dos de las principales causas del declive de la especie. Aunque no ha sido declarada oficialmente extinta, la mariposa no se ha visto desde hace décadas.",
    "CIERVO": "El ciervo de Schomburgk: Es originario de Tailandia y recibe su nombre del explorador de origen alemán Sir Robert H. Schomburgk, nombrado caballero en 1844. Algunos científicos creen que todavía pueden existir algunos de estos ciervos en la naturaleza, aunque fueron declarados oficialmente extintos en 2006 y el último ciervo conocido se mató en cautividad en 1938. Causa de la extinción: Además de los humanos, el ciervo de Schomburgk era cazado por tigres y leopardos autóctonos. En la actualidad, sólo se conoce una cabeza de ciervo montada que reside en el Museo Nacional de Historia Natural de París.",
    "DODO": "El Dodo: Era un ave no voladora originaria de Mauricio cuya población empezó a disminuir y acabó por extinguirse en el breve transcurso de un siglo, cuando los marineros empezaron a llegar a esta nación insular de África oriental. Los últimos dodos fueron vistos en la década de 1660 y, debido a que no se hizo hincapié en la conservación de los especímenes, muchos de los fósiles restantes se perdieron o fueron destruidos. Aunque el dodo se extinguió hace más de 150 años, su historia es importante. La gente no creía que Dios le quitara la existencia a una criatura después de haberse tomado la molestia de crearla, así que nadie se alarmó realmente por su desaparición. Esto llevó a la gente a creer que había más dodos escondidos en algún lugar de la naturaleza y, por lo tanto, los especímenes no se manejaron con el cuidado que deberían haber tenido. Causa de la extinción: la creencia popular dice que los marineros cazaron y se comieron al dodo hasta extinguirlo, pero es más probable que las ratas (y otros animales) que los marineros trajeron con ellos causaran el declive del dodo. La BBC informa de que las ratas probablemente se comieron los huevos del dodo y otros animales superaron al ave en cuanto a fuentes de alimento.",
    "TORTUGA": "Tortuga gigante de Pinta: Existía cuando Darwin visitó las Galápagos en 1835. Lamentablemente, un macho llamado Solitario Jorge (en la foto), fue el último ejemplar puro de esta subespecie y falleció en 2015. Causa de la extinción: las cabras que los humanos introdujeron en la isla Pinta y que destruyeron sus hábitats, las ratas (también introducidas por los humanos) que se cebaron con las tortugas jóvenes y los humanos que mataron a las tortugas por su carne.",
    "PEZ": "El pez cachorro de Tecopa: Nativo de las aguas termales del desierto de Mojave, tiene el honor de ser el primer animal declarado extinto en virtud de las disposiciones de la Ley de Especies en Peligro de 1973. El declive del pez cachorro se precipitó cuando su hábitat natural fue invadido por promotores. Causa de la extinción: la destrucción de su hábitat natural.",
    "COTORRA": "La cotorra de Carolina: Era el único pájaro de su clase nativo de la parte oriental de EE.UU. La última murió en el zoológico de Cincinnati en febrero de 1918, poco después de que falleciera su compañera, Lady Jane. Causa de la extinción: el Smithsonian señala que, aunque no hay una razón específica que explique la extinción de esta cotorra, es probable que la deforestación y las enfermedades sean las que acabaron con estos pájaros de brillantes colores. Tampoco ayudó el hecho de que sus plumas fueran codiciadas para los sombreros de las mujeres.",
    "QUAGGA": "El Quagga: Era originario de Sudáfrica y se extinguió a finales del siglo XIX. Durante mucho tiempo se pensó que el quagga era su propia especie, antes de que se descubriera que estaba estrechamente relacionado con la cebra de las llanuras y que, de hecho, era una subespecie de la cebra. El aspecto del quagga era interesante, ya que literalmente parecía la mezcla de dos animales: una cebra en la parte delantera, gracias a las famosas rayas de cebra que adornan esta parte de su cuerpo, y un caballo en la parte trasera, debido a la falta de rayas en esta zona. Los científicos están tratando de resucitar al quagga y han tenido cierto éxito mediante la ingeniería inversa, criando selectivamente cebras (que llevan genes de quagga). Causa de la extinción: los humanos cazaron al quagga hasta su extinción.",
};

const words = Object.keys(wordsInfo);